### PR TITLE
Add spring-jcl to slf4j enforcement substitution

### LINKED ISSUE #36: Enforcement no longer works with spring-jcl
The recent change to handle `spring-jcl` has caused a regression when using `enforceLogback`. After updating lockfiles I now see that `spring-jcl` has been removed from `runtimeClasspath`, however it is left intact for `compileClasspath`, which causes this problem during build time:
```
> Could not resolve all files for configuration ':foo:compileClasspath'.
   > Did not resolve 'org.springframework:spring-jcl:5.3.26' which is part of the dependency lock state
   > Resolved 'org.slf4j:jcl-over-slf4j:1.7.36' which is not part of the dependency lock state
```

### PR DESCRIPTION
**Pull request by cmuchinsky**
Fixes https://github.com/ljacomet/logging-capabilities/issues/36

### CODE REVIEW

**Comment by cmuchinsky** [comment]
@ljacomet does this seem like a reasonable fix for the related issue?

**Review by ljacomet — APPROVED** [review]
Changes look good, thanks for the contribution!

Will merge unless test do not pass.

**Comment by cmuchinsky** [comment]
Thanks @ljacomet, any chance of getting this released as a `0.11.1` patch prior to the larger `0.12.0` milestone that is planned?

**Comment by madorb** [comment]
have been bitten by this many many times recently and have had to add spring-jcl exclusions to many apps. would love to see a point release

**Comment by ljacomet** [comment]
[Done](https://plugins.gradle.org/plugin/dev.jacomet.logging-capabilities/0.11.1)

**Pull request merged**
